import { ObjectType, Field, Int, registerEnumType } from '@nestjs/graphql';
import { BookingWindow } from '../schemas/booking-availability-config.schema';
import { ProviderType } from '../../online-orders/schemas/order-status.enum';

/**
 * Read models: the *resolved* view of a provider's booking availability, after
 * weekly rules, date overrides, blackouts, the pause switch, lead time,
 * same-day cutoff, advance window and capacity have all been applied.
 *
 * The config documents say what a provider configured; these say what a
 * customer can actually book. Keeping them apart is what lets §14's preview
 * ("what customers see") be generated by the same code path the real booking
 * check runs, instead of a second implementation that drifts.
 */

/** Why a day is unavailable. Drives the customer-facing wording. */
export enum UnavailableReason {
  BOOKINGS_DISABLED = 'bookings_disabled',
  BOOKINGS_PAUSED = 'bookings_paused',
  CLOSED_THIS_DAY = 'closed_this_day',
  BLACKED_OUT = 'blacked_out',
  DAY_FULLY_BOOKED = 'day_fully_booked',
  PAST_CUTOFF = 'past_cutoff',
  INSUFFICIENT_NOTICE = 'insufficient_notice',
  BEYOND_ADVANCE_WINDOW = 'beyond_advance_window',
  IN_THE_PAST = 'in_the_past',
  FULFILLMENT_UNAVAILABLE = 'fulfillment_unavailable',
}
registerEnumType(UnavailableReason, { name: 'UnavailableReason' });

/** One date in the availability calendar, resolved. */
@ObjectType()
export class BookingDayAvailability {
  /** 'YYYY-MM-DD' PH-local. */
  @Field() date!: string;
  /** 'monday' … 'sunday'. */
  @Field() dayOfWeek!: string;
  @Field() isBookable!: boolean;
  @Field(() => UnavailableReason, { nullable: true })
  unavailableReason?: UnavailableReason;

  /** The windows in force for this date, after any override. */
  @Field(() => [BookingWindow]) windows!: BookingWindow[];

  /**
   * NULL MEANS UNLIMITED — the common case, since a provider with no cap of
   * her own inherits an uncapped entitlement.
   *
   * These were non-null Int, and the service represents "no cap" as
   * Number.POSITIVE_INFINITY so that `remaining > 0` works. GraphQL cannot
   * serialize Infinity as an Int, so the whole query threw and every caller saw
   * a failure instead of a calendar. Infinity stays internal; the boundary says
   * null.
   */
  @Field(() => Int, { nullable: true }) dailyBookingLimit?: number | null;
  @Field(() => Int) bookedCount!: number;
  @Field(() => Int, { nullable: true }) remaining?: number | null;

  /** True when a date override or blackout applies — the UI marks these. */
  @Field() isSpecialDate!: boolean;
  @Field({ nullable: true }) specialDateLabel?: string;

  @Field() providerPickupAvailable!: boolean;
  @Field() providerDeliveryAvailable!: boolean;
  @Field() customerDropoffAvailable!: boolean;
  @Field() customerPickupAvailable!: boolean;
}

/**
 * §15 — the configuration restated in plain language, generated server-side so
 * the admin panel, the partner app and any future surface all read the same
 * sentences. A provider who has to reverse-engineer her own setup from seven
 * day-rows and six rule fields will misconfigure it.
 */
@ObjectType()
export class BookingRulesSummary {
  /** e.g. ['Mon–Fri  8:00 AM – 8:00 PM', 'Sat  9:00 AM – 5:00 PM', 'Sun  Closed'] */
  @Field(() => [String]) scheduleLines!: string[];
  /** e.g. ['30-minute booking intervals', 'Maximum 3 bookings per slot', …] */
  @Field(() => [String]) ruleLines!: string[];
  /** 'Accepting bookings' | 'Bookings paused' | 'Not accepting bookings' */
  @Field() stateLabel!: string;
  @Field() isAcceptingBookings!: boolean;
}

/**
 * One row of the admin page's provider picker.
 *
 * Keyed by branchId, which is what booking configs are keyed by — the KYC
 * monitoring rollup keys washers by their PROFILE id instead, so reusing it
 * here would hand the config queries an id they cannot resolve.
 */
@ObjectType()
export class BookingProviderRow {
  @Field() branchId!: string;
  /**
   * Was a plain `string` field: the service assigns the ProviderType enum's
   * VALUE ('washer'/'merchant', lowercase) to it, and a plain string field
   * serializes that raw value rather than the enum's uppercase GraphQL name.
   * The admin panel filters on the uppercase form and silently got zero rows
   * back for every washer — this page has shown "No home washers yet." no
   * matter how many existed. Declaring the real enum type fixes the
   * serialization; nothing about the service's assignment needs to change.
   */
  @Field(() => ProviderType) providerType!: ProviderType;
  @Field() name!: string;
  /** False when the provider has never been configured and is on defaults. */
  @Field() isConfigured!: boolean;
  /** 'Accepting bookings' | 'Bookings paused' | 'Not accepting bookings' */
  @Field() stateLabel!: string;
  /**
   * Admin's per-washer daily order cap, or null for no cap. WASHER rows only —
   * always null for a laundromat, whose throughput is its own business.
   *
   * Carried on this row so the admin screen can show and edit the cap from the
   * provider list it already renders. Null is a real state, not "unknown": there
   * is no platform default behind it (see WasherService.setDailyOrderCap).
   */
  @Field(() => Int, { nullable: true }) maxOrdersPerDay?: number | null;
  /**
   * WasherStatus ('ACTIVE' | 'INACTIVE' | 'SUSPENDED'), WASHER rows only —
   * always null for a laundromat. Carried here for the same reason
   * maxOrdersPerDay is: the admin panel edits washer account status from this
   * same provider list (see WasherService.setStatus).
   */
  @Field(() => String, { nullable: true }) washerStatus?: string | null;
}

/** A blackout flattened for display alongside overrides in one list. */
@ObjectType()
export class UpcomingSpecialDate {
  @Field() date!: string;
  @Field({ nullable: true }) label?: string;
  @Field() isClosed!: boolean;
  /** 'Closed' | 'Special schedule' | 'Reduced capacity' */
  @Field() kind!: string;
  @Field() detail!: string;
  /** 'override' | 'blackout' — which record to edit. */
  @Field() source!: string;
  @Field({ nullable: true }) recordId?: string;
}

/**
 * Generic customer wording for a day-level reason.
 *
 * Deliberately separate from `explain()` in the service, which is
 * entitlement-aware and names the provider's actual cutoff and notice period.
 * That precision is worth a lookup when a booking is being REFUSED; a calendar
 * rendering seven days at once should not pay for seven entitlement reads to
 * caption days the customer can simply not tap.
 */
export function explainUnavailable(reason: UnavailableReason): string {
  switch (reason) {
    case UnavailableReason.BOOKINGS_DISABLED:
      return 'Not accepting bookings';
    case UnavailableReason.BOOKINGS_PAUSED:
      return 'Bookings paused';
    case UnavailableReason.CLOSED_THIS_DAY:
      return 'Closed';
    case UnavailableReason.BLACKED_OUT:
      return 'Unavailable';
    case UnavailableReason.DAY_FULLY_BOOKED:
      return 'Fully booked';
    case UnavailableReason.PAST_CUTOFF:
      return 'Same-day bookings closed';
    case UnavailableReason.INSUFFICIENT_NOTICE:
      return 'Too soon';
    case UnavailableReason.BEYOND_ADVANCE_WINDOW:
      return 'Too far ahead';
    case UnavailableReason.IN_THE_PAST:
      return 'Past';
    case UnavailableReason.FULFILLMENT_UNAVAILABLE:
      return 'Pickup not offered';
    default:
      return 'Unavailable';
  }
}
